#+TITLE: 维克多和威克的来往信件

** 维克多和威克的来往信件

致威克：
　　嘿，伙计，大家都夸我们是好搭档！
　　不过我觉得你实在太贪吃了。要不是你上次只顾着把盘里的香肠油汁舔个精光，我们也不会错过递送时间了。
　　邮差可不能迟到！
　　身为邮差，就要自觉、自省、自律，专注于本职工作——我们的目标就是信，哪怕再次身临那场火灾也一样不能退缩！
　　我不太会说话，只能用行动来回应大家的信任。所以，拿出我们的决心好么，伙计！
  
  另：
 　　……顺便给我写一封信吧。当然，你只管“说”，内容就由我来代笔记录怎么样？那就——开始吧！

你的搭档
维克多

致维克多：
 　　汪汪汪呜，呜，汪汪，呜呜，汪，汪汪呜汪，呜呜鸣，汪呜汪，呜江汪，汪汪，鸣汪，呜汪，汪，汪呜汪——?
   
你的搭档
威克
** Letter correspondence between Victor and Wick

To Wick:
Hey, buddy. Everyone says we're such good partners!
But I think you're eating too much. We wouldn't have missed the delivery deadline if you weren't busy licking the sausage sauce from the plate. 
A postman should never be late!
As a postman, we must we self-aware, self-reflective, self-disciplined and focus on our job — our goal is all about the delivery of letters. We can't retreat even if we had to go back to the fire!
I'm not good with words, so I can only repay le's trust with actions.
Therefore, we must put our heart into our work, partner!

P.S.
...just write something back. Of course, you'll only have to"say the words" and I'll put it on paper. How's that? So...Let's begin!

Your partner,
Victor

To Victors:
Woof woof woof ruff, ruff, woof woof, ruff ruff, woof, woof woof ruff woof, ruff ruff ruff, woof ruff woof, ruff woof woof, woofwoof, ruff woof, ruff woof, woof, woof ruff woof—?

Your partner,
Wick